name: Deploy Hugo (PaperMod) to Pages repo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true         # подтягиваем themes/PaperMod
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo -D -b "https://wizoomm.github.io/"

      - name: Deploy to wizoomm.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: wizoomm/wizoomm.github.io
          publish_branch: main
          publish_dir: ./public
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

